# Changes here will be overwritten by Copier
_commit: 1.2.0
_src_path: gh:pawamoy/copier-pdm
author_email: pawamoy@pm.me
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2022'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
insiders: false
project_description: A PDM plugin to run a command on multiple Python versions.
project_name: PDM Multirun
python_package_command_line_name: ''
python_package_distribution_name: pdm-multirun
python_package_import_name: pdm_multirun
repository_name: pdm-multirun
repository_namespace: pawamoy
repository_provider: github.com

